[pytest]
addopts = -v -s --html=report.html --self-contained-html --tb=short
testpaths = steps
python_files = *_steps.py
python_functions = test_*
markers =
    smoke: Smoke tests
    regression: Regression tests
    admin: Admin module tests
    pim: PIM module tests
    leave: Leave module tests
    profile: Profile module tests
    critical: Critical path tests